version: "3.9"
services:
  fastapi:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/src
      - pycache:/venv

volumes:
  pycache:
